### ISSUE TITLE
Reduntant if statement wrapping

### ISSUE THREAD

**Issue by eko24ive** [Artinov/home-work-13-kramarmm#2]
Mostly all your code is wrapped inside this `if`:
```js
if (request.url !== '/favicon.ico') {
```

The important part is you don't have any procedures for this situation, which means you never "end" request for `/favicon.ico` which kinda bad practice, because it will end by himself when this request reaches its timeout.

Also this actually brings us to additional intending in code. Therefore, this may complex our comfort with code reading in future.

This could be simplified to following:
```js
if (request.url !== '/favicon.ico') {
    response.end();
    return;
}
```

Now we're ending request on our own. And we don't have to write else statement where we can put rest of our code because we using `return;` statement which as we know - makes all code which placed below "unreachable" if only our app will come into this if statement.

**Comment by kramarmm** [comment]
fixed
