### ISSUE TITLE
UX: Validation of given operator

### ISSUE THREAD

**Issue by eko24ive** [Artinov/home-work-13-kramarmm#3]
You already handling if user "gave" you exactly two numbers which is really cool and right the thing to do.
But in your `switch` statement you've described only four cases for common arithmetic operators ( +, -, *, / ).
But as long as you don't have `default` case for this `switch` - you don't notifying user properly about this, actually website even mislead him by telling that:
```
Only numbers can be calculate.
Please, enter a number.
```

Which may be frustrating for him, becouse if I go to `http://localhost:3000/1%1` I'm sure that I've typed two numbers and math symbol, but probably I've missed the right key on keyboard (which I don't know yet). And website tells me that something wrong with my numbers when actually root of issue - wrong symbol.

So, this could be handled via `default`, which could send to user response message which countains user-friendly error description and list of acceptable math operators. Also you may expand your "hello" message at the main page wtih same list of possible operators. This will significanlty increase UX.

**Comment by kramarmm** [comment]
Thank you for issues! I will fix it.

**Comment by kramarmm** [comment]
Fixed
https://github.com/Artinov/home-work-13-kramarmm/commit/a10fcfb09b80e67a52d248f2f8fa45b2afd695bb
